### ISSUE TITLE
need a way to send ^C or ^D to a running command

### ISSUE THREAD

**Issue by adbennet** [ColdGrub1384/LibTerm#1]
I cannot figure out how to send ^C,^D etc. using logitech K380 keyboard, nor with ios soft keyboard. Believe me I tried every key combination. OpenTerm has a "Stop" on the input assistant suggestions bar, which sends ^C (I would usually prefer ^D, so that awk will run the END pattern). Here is a simple scenario reading stdin, the only way out that I can think of is to close the tab:
$ awk -- '{print NR, $0;}'
foo
1 foo
bar
2 bar
how to exit?
3 how to exit?
Edit: Actually, I'm not sure if closing the tab is sufficient, it seems to leave stdout in other tab messed up.

**Comment by adbennet** [comment]
Thanks a bunch. I'll take the Ctrl-C/Stop, it will be useful in so many situations. I needed it a couple of times today! But it seems Ctrl-D should be possible, is there a way to echo an Ascii-0x04 to stdin from the suggestions bar? It might just work.

**Comment by ColdGrub1384** [comment]
Sending CTRL-D to the stdin shouldn't work because the program will just receive 0x04. But the kernel should handle CTRL-D and send a signal to the program. I think in a normal terminal, the kernel detects a CTRL-D from the stdin and sends a signal to the program but the program doesn't receive 0x04. All processes are ran in the same terminal's process in this iOS app due to sandbox, so it's impossible to send signals. I'm adding a "Stop" button wich kills the thread running the program (or just the function here).

**Comment by adbennet** [comment]
Okay I will take your word for it. I was reading about CTRL-D but did not understand all of it.
https://unix.stackexchange.com/questions/110240/why-does-ctrl-d-eof-exit-the-shell

**Comment by ColdGrub1384** [comment]
Fixed by c7a2cea98776c76026925a8ca5c2b6a5da168026

**Comment by nkorth** [comment]
The stop button isn't a good solution - what if the suggestion bar is disabled?

Also, ^D doesn't send a signal, it sends the EOF character which many interactive programs interpret as "quit". It's useful to have a way to send this character.
