### ISSUE TITLE
Is there a built in editor like nano or vim?

### ISSUE THREAD

**Issue by Shock9616** [ColdGrub1384/LibTerm#6]
I am just curious if there is a text editor built in to LibTerm such as nano or vim. If not, would it be possible to create one or would iOS restrict that?

**Comment by ColdGrub1384** [comment]
No there isn't for now. Vim and nano would be very difficult to integrate in LibTerm because, basically, the delete key doesn't work on LibTerm. I mean, when input is sent, the app waits the user tap "Return" because I could not make the backspace key work. Also for the cursor, and the terminal. iOS doesn't restrict that. In a separate app just made for running vim, it's easier and there are vim ports for iOS: https://itunes.apple.com/us/app/ivim/id1266544660?mt=8.

I will add a graphic text editor with syntax highlighting in LibTerm.

**Comment by Shock9616** [comment]
Ok thank you. I just want to be able to edit files from the command line.

**Comment by RunningUtes** [comment]
I really love iVim and use it daily. Is there any chance you and the author of iVim could collaberate on a project to merge the two apps together.
