### ISSUE TITLE
Is there anywhere a cursor up button for Command history?

### ISSUE THREAD

**Issue by halloleo** [ColdGrub1384/LibTerm#61]
Playing with LibTerm and it is pretty impressive! :-)

Just wondering wether there is a "cursor up" button on the soft keyboard for editing the last command. Or is there any other form of Command History for editing?

**Comment by captain** [comment]
It appears that if you have suggestions turned on, your command History is right there at the top of your softkeyboard.  There also appears to be some kind of a "swipe up" from the space bar. Apparently, they don't think we need arrow keys because we can tap on the screen to put the cursor right where we want it, and you can select character/words/entire lines, and backspace them away. It takes a little getting used to, but it seems mostly functional.  I wonder if attaching a Bluetooth keyboard would work as expected.

**Comment by halloleo** [comment]
Thanks for the information. I will try it out.
