### ISSUE TITLE
VT100  support

### ISSUE THREAD

**Issue by xiongxiongjiang** [ColdGrub1384/LibTerm#8]
Can this terminal support VT100 ?

**Comment by ColdGrub1384** [comment]
This terminal supports `ANSI`. I don't know how it could support `VT100` but there is a JavaScript library for `xterm` called `xterm.js` for implementing an `xterm` terminal in HTML. I use it in an SSH client in a Web View. I don't think it's necessary to implement `VT100` or `xterm` in this terminal because there is no command that needs it.

**Comment by xiongxiongjiang** [comment]
ok,thx~
