### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by goerz** [ColdGrub1384/LibTerm#9]
Would you be opposed to embedding Python 3 instead of Python 2? Python 2 is going to be dead next year, and I don't think a lot of people still want to stick to Python 2 for any new scripts. See also the discussion at https://github.com/blinksh/blink/issues/555#issuecomment-445501018

**Comment by ColdGrub1384** [comment]
I'm planning to do that. I have embedded Python 2.7 because `ios_system` does it, but I would also prefer Python 3.7. @holzschu has a repo for building Python 3.6: https://github.com/holzschu/python3_ios. 
I will try to compile it and embed it on LibTerm. There is a repo that contains many Python versions prebuilt for iOS: https://github.com/pybee/Python-Apple-support/tree/3.7. I use its binary in [Pyto](https://github.com/ColdGrub1384/Pyto), a Python 3.7 IDE I made, but it's the API, not the command. It could be embedded on LibTerm because there is a `python_main` function but the stdout, stderr and stdin would not be redirected. In Pyto, I have put a Python script that redirects only Python output and input. So, it's not for being used with `ios_system`.

**Comment by ColdGrub1384** [comment]
I just opened this issue: https://github.com/holzschu/python3_ios/issues/1.

**Comment by ColdGrub1384** [comment]
Good news! I successfully embedded Python 3.7! I will commit soon

**Comment by ColdGrub1384** [comment]
Updated to Python 3.7!!! 03853d0
